version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    environment:
      - CI=false